### ISSUE TITLE
Extend make prepare for standalone modes

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_kitodo#41]
Extend the `make prepare` target to support standalone of OCR-D Controller and Kitodo.Production.

**Comment by bertsky** [comment]
In other words: if Controller and/or Production is not managed by docker-compose here, at least support managing the access credentials and user data for the independent modules via the makefile.

**Comment by bertsky** [comment]
We've done that, haven't we?

Or is there any way to get `make-data` usable for external/remote Kitodo.Production instances?
