### ISSUE TITLE
Controller does not expose SSH Port

### ISSUE THREAD

**Issue by SvenMarcus** [slub/ocrd_kitodo#68]
When launching the meta-repository with `make start` the controller does not expose the port set in `CONTROLLER_PORT_SSH` to the host, making it unusable over the network.
There is a `docker-compose.override.yml` in `_modules/ocrd_controller` that exposes this port, but it is not being loaded, since the `ocrd-controller` service in our base `docker-compose.yml` explicitly extends `_modules/ocrd_controller/docker-compose.yml`.

**Comment by markusweigelt** [comment]
The port is exposed to the default network so every service in that network can reach the OCR-D Controller over port `22` as default (https://github.com/slub/ocrd_controller/blob/master/Dockerfile#L58) without explizit exposing in docker-compose.yml. 

Please consider following discussion to the current implementation https://github.com/slub/ocrd_kitodo/commit/02162ad26b49e5db6f8a3accece5e06b714af992 Can the ticket be closed?

**Comment by SvenMarcus** [comment]
So, if the manager runs on a separate machine, as will probably be the default, considering that not every institution can provide a controller, what would be the proper configuration on the controller host side to enable communication from outside the local or docker network?

**Comment by markusweigelt** [comment]
The documentation "Integration of OCR-D and Kitodo" describes how to set up an external controller instance and connect the manager. https://slub.github.io/ocrd_kitodo/setup/configure-external/#configuring-an-external-ocr-d-controller-instance

Also feel free to make suggestions if something is not understandable.

**Comment by SvenMarcus** [comment]
So the idea is to use the `ocrd_controller` repository directly?
I was under the assumption that the meta-repository was supposed to be able to launch all the possible configurations on its own.

**Comment by markusweigelt** [comment]
Yes or the native installation ocrd_all with SSH server.

IMO we should separate the native installation in the documentation and not support it, because we can't cover it with our CI.

All further services can then be started via the meta-repository. https://slub.github.io/ocrd_kitodo/setup/enable-disable-modules/
For the external Kitodo.Production it behaves the same way. Only OCR-D Manager and the OCR-D Monitor are mandatory.

**Comment by markusweigelt** [comment]
No need for a fix. If this issue is still present, please reopen.
