### ISSUE TITLE
Cannot launch without controller

### ISSUE THREAD

**Issue by SvenMarcus** [slub/ocrd_kitodo#70]
The `ocrd-manager` and `ocrd-monitor` services depend on the `ocrd-controller` service.
Therefore, I cannot launch the docker compose configuration without activating the controller.

**Comment by bertsky** [comment]
Really? What error message do you get?

AFAIK (and by my experience) these dependencies have no effect for services from disabled profiles.

**Comment by markusweigelt** [comment]
If I delete the `with-ocrd-controller profile from the Makefile and start it, all services except the controller are started. Is it different for you?

**Comment by bertsky** [comment]
> If I delete the `with-ocrd-controller` profile from the Makefile and start it

No need to edit the makefile! Just set COMPOSE_PROFILES in your shell.

**Comment by markusweigelt** [comment]
> No need to edit the makefile! Just set COMPOSE_PROFILES in your shell.

That's the royal road for the test, it was sufficient. :innocent:

**Comment by SvenMarcus** [comment]
Oh sorry, it was a mistake on my part. I accidentally read the wrong line in the documentation when looking up the default profile and ended up assuming it was just manager/monitor 🙃

One thing that we need to have a look at though, is that I need to define the controller variables in my `.env` despite disabling the controller.
I get the following errors:
```
WARN[0000] The "CONTROLLER_BASE_VERSION" variable is not set. Defaulting to a blank string.
WARN[0000] The "CONTROLLER_IMAGE" variable is not set. Defaulting to a blank string.
WARN[0000] The "CONTROLLER_ENV_UMASK" variable is not set. Defaulting to a blank string.
WARN[0000] The "CONTROLLER_WORKERS" variable is not set. Defaulting to a blank string.
WARN[0000] The "CONTROLLER_WORKERS" variable is not set. Defaulting to a blank string.
3 error(s) decoding:

* error decoding 'Volumes[1]': invalid spec: :/models: empty section between colons
* error decoding 'Volumes[2]': invalid spec: :/config: empty section between colons
* error decoding 'Volumes[3]': invalid spec: :/data: empty section between colons
```

**Comment by markusweigelt** [comment]
Errors will be avoided with following pr https://github.com/slub/ocrd_controller/pull/27

**Comment by markusweigelt** [comment]
Problem is fixed and merge into the master branch of controller repo. Please reopen if there is still a problem here.
